trigger: none
pr: none

parameters:
  - name: commitSHA
    displayName: Commit SHA
    type: string
  - name: environment
    displayName: Environment
    type: string
  - name: pool
    displayName: ADO management pool
    type: string

stages:
  - stage: ${{ parameters.environment }}
    displayName: Deploy Arc infrastructure to ${{ parameters.environment }}
    pool:
      name: ${{ parameters.pool }}
    lockBehavior: sequential
    isSkippable: false

    jobs:
      - deployment: DeployArcInfra
        displayName: Deploy Arc infrastructure
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - bash: |
                    TF_VERSION=$(grep "^terraform" .tool-versions | awk '{print $2}')
                    echo "##vso[task.setvariable variable=TF_VERSION]$TF_VERSION"
                  displayName: Get Terraform version from .tool-versions

                - task: TerraformInstaller@1
                  displayName: Install Terraform
                  inputs:
                    terraformVersion: $(TF_VERSION)

                - task: AzureCLI@2
                  displayName: Run Terraform
                  inputs:
                    azureSubscription: manbgw-${{ parameters.environment }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    inlineScript: |
                      export ARM_TENANT_ID="$tenantId"
                      export ARM_CLIENT_ID="$servicePrincipalId"
                      export ARM_OIDC_TOKEN="$idToken"
                      export ARM_USE_OIDC=true
                      make ci ${{ parameters.environment }} terraform-apply
